services:
  - type: web
    name: filesys-backend
    env: node
    buildCommand: npm install
    startCommand: node start.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000 